import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from http_diff import *

def scenario(rn):
    c = rn.call
    c('index', 'GET', '/'); c('manifest', 'GET', '/manifest.webmanifest'); c('sw', 'GET', '/sw.js'); c('offline', 'GET', '/static/offline.html')
    c('static app.js', 'GET', '/static/app.js'); c('static style', 'GET', '/static/style.css'); c('icon', 'GET', '/static/icons/icon-192.png')
    c('404', 'GET', '/nincs'); c('static 404', 'GET', '/static/nincs.js'); c('method', 'POST', '/')
    c('me anon', 'GET', '/api/auth/me'); c('profile anon', 'GET', '/api/auth/profile'); c('socket-token anon', 'GET', '/api/auth/socket-token')
    c('request-code ok', 'POST', '/api/auth/request-code', json_body={'email': 'new1@example.com'})
    c('request-code bad', 'POST', '/api/auth/request-code', json_body={'email': 'nemcim'})
    c('request-code empty', 'POST', '/api/auth/request-code', json_body={})
    c('request-code non-json', 'POST', '/api/auth/request-code', data='x=1')
    c('verify bad', 'POST', '/api/auth/verify-code', json_body={'email': 'new1@example.com', 'code': '000000'})
    c('verify short', 'POST', '/api/auth/verify-code', json_body={'email': 'new1@example.com', 'code': '12'})
    c('register no verify', 'POST', '/api/auth/register', json_body={'email': 'new2@example.com', 'password': 'secret12', 'display_name': 'Uj'})
    c('login bad', 'POST', '/api/auth/login', json_body={'email': 'u1@example.com', 'password': 'rossz'})
    c('login unknown', 'POST', '/api/auth/login', json_body={'email': 'senki@example.com', 'password': 'rossz'})
    c('login empty', 'POST', '/api/auth/login', json_body={})
    c('login ok', 'POST', '/api/auth/login', who='u1', json_body={'email': 'u1@example.com', 'password': 'secret12'})
    c('me', 'GET', '/api/auth/me', who='u1'); c('profile', 'GET', '/api/auth/profile', who='u1'); c('socket-token', 'GET', '/api/auth/socket-token', who='u1')
    c('leaderboard', 'GET', '/api/leaderboard'); c('leaderboard wins', 'GET', '/api/leaderboard?metric=wins&limit=5'); c('leaderboard bad', 'GET', '/api/leaderboard?metric=zzz')
    c('leaderboard auth', 'GET', '/api/leaderboard?metric=rating', who='u1')
    c('dict check', 'GET', '/api/dictionary/check?q=alma'); c('dict check bad', 'GET', '/api/dictionary/check?q=%27%3B'); c('dict check none', 'GET', '/api/dictionary/check')
    c('dict check words', 'POST', '/api/dictionary/check', json_body={'words': ['alma', 'körte', 'xyzzy', 'faalma']})
    c('dict check too many', 'POST', '/api/dictionary/check', json_body={'words': ['a'] * 20})
    c('dict check kg', 'GET', '/api/dictionary/check?q=kg'); c('dict check brr', 'GET', '/api/dictionary/check?q=brr'); c('dict check falim', 'GET', '/api/dictionary/check?q=falim')
    c('dict check szo', 'GET', '/api/dictionary/check?q=Duna'); c('dict check long', 'GET', '/api/dictionary/check?q=' + 'a' * 40)
    c('announcements', 'GET', '/api/announcements'); c('announcements u1', 'GET', '/api/announcements', who='u1')
    c('daily anon', 'GET', '/api/daily'); c('daily u1', 'GET', '/api/daily', who='u1'); c('daily lb', 'GET', '/api/daily/leaderboard')
    c('daily lb bad', 'GET', '/api/daily/leaderboard?date=nemdatum'); c('daily lb date', 'GET', '/api/daily/leaderboard?date=2026-01-01')
    c('quiz', 'GET', '/api/practice/quiz?n=10&mode=mixed'); c('quiz bad', 'GET', '/api/practice/quiz?n=999&mode=zzz'); c('quiz 2', 'GET', '/api/practice/quiz?n=5&mode=2')
    c('answer', 'POST', '/api/practice/answer', json_body={'word': 'alma', 'answer': True}); c('answer bad', 'POST', '/api/practice/answer', json_body={})
    c('answer no', 'POST', '/api/practice/answer', json_body={'word': 'almaz', 'answer': True})
    c('short words 2', 'GET', '/api/practice/short-words?length=2'); c('short words 3', 'GET', '/api/practice/short-words?length=3'); c('short bad', 'GET', '/api/practice/short-words?length=5')
    c('rack hunt', 'GET', '/api/practice/rack?kind=hunt'); c('rack bingo', 'GET', '/api/practice/rack?kind=bingo'); c('rack bad', 'GET', '/api/practice/rack?kind=x')
    c('rack-word', 'POST', '/api/practice/rack-word', json_body={'rack': ['A', 'L', 'M', 'A', 'K', 'E', 'T'], 'word': 'alma'})
    c('rack-word bad', 'POST', '/api/practice/rack-word', json_body={'rack': ['A'], 'word': 'alma'})
    c('rack-word none', 'POST', '/api/practice/rack-word', json_body={})
    c('word-review anon', 'GET', '/api/practice/word-review'); c('word-review u1', 'GET', '/api/practice/word-review?n=3', who='u1')
    c('word-review stats', 'GET', '/api/practice/word-review/stats', who='u1')
    c('word-review vote bad', 'POST', '/api/practice/word-review', who='u1', json_body={'word': 'alma', 'valid': True})
    c('word-review vote nowa', 'POST', '/api/practice/word-review', who='u1', json_body={})
    c('word-review undo', 'POST', '/api/practice/word-review/undo', who='u1', json_body={'word': 'alma'})
    c('push key', 'GET', '/api/push/public-key', who='u1'); c('push key anon', 'GET', '/api/push/public-key')
    c('push sub bad', 'POST', '/api/push/subscribe', who='u1', json_body={'endpoint': 'x'})
    c('push sub anon', 'POST', '/api/push/subscribe', json_body={})
    c('push unsub', 'POST', '/api/push/unsubscribe', who='u1', json_body={'endpoint': 'x'})
    c('async games', 'GET', '/api/async/games', who='u1'); c('async anon', 'GET', '/api/async/games')
    c('game moves 404', 'GET', '/api/game/9999/moves'); c('game share 404', 'POST', '/api/game/9999/share', who='u1'); c('replay 404', 'GET', '/api/replay/abc')
    c('analysis 404', 'GET', '/api/game/9999/analysis'); c('analysis string', 'GET', '/api/game/abc/analysis')
    c('logout', 'POST', '/api/auth/logout', who='u1'); c('me after logout', 'GET', '/api/auth/me', who='u1')
    # tévedés-kezelés
    c('admin 404 anon', 'GET', '/admin'); c('admin api 404 anon', 'GET', '/api/admin/overview'); c('admin asset anon', 'GET', '/admin/assets/admin.js')

if __name__ == '__main__':
    run_all(scenario, 'h1_public', 120)
