import os, sys; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from http_diff import *

def scenario(rn):
    def A(label, method, path, body=None, who='admin'):
        return rn.call(label, method, '/api/admin' + path, who=who, json_body=body, admin=True)
    for u in ('u1', 'u2', 'u3'):
        rn.call('login ' + u, 'POST', '/api/auth/login', who=u, json_body={'email': f'{u}@example.com', 'password': 'secret12'})
    rn.call('login admin', 'POST', '/api/auth/login', who='admin', json_body={'email': 'admin@example.com', 'password': 'secret12'})
    # nem admin
    for p in ('/overview', '/users', '/session', '/audit', '/nincs', '/users/1', '/system'):
        A('nonadmin ' + p, 'GET', p, who='u1')
    A('nonadmin post', 'POST', '/sudo', {'password': 'x'}, who='u1')
    rn.call('nonadmin page', 'GET', '/admin', who='u1'); rn.call('nonadmin asset', 'GET', '/admin/assets/admin.js', who='u1')
    # csrf
    rn.call('csrf missing', 'POST', '/api/admin/sudo', who='admin', json_body={'password': 'secret12'})
    rn.call('csrf bad origin', 'POST', '/api/admin/sudo', who='admin', json_body={'password': 'secret12'}, headers={'X-Admin-Request': '1', 'Origin': 'http://evil.example'})
    rn.call('admin page', 'GET', '/admin', who='admin'); rn.call('admin asset', 'GET', '/admin/assets/admin.js', who='admin')
    rn.call('admin asset 404', 'GET', '/admin/assets/nincs.js', who='admin'); rn.call('admin double slash', 'GET', '//admin', who='admin')
    A('wrong method', 'PUT', '/overview'); A('unknown', 'GET', '/nincs-ilyen')
    A('session', 'GET', '/session')
    GETS = ['/overview', '/charts', '/charts?days=7', '/charts?days=1', '/search?q=jatekos', '/search?q=1', '/search?q=' + 'a' * 70, '/search?q=alma',
            '/users', '/users?q=jatekos2', '/users?status=banned', '/users?status=zzz', '/users?sort=email&order=asc&limit=2', '/users?online=1',
            '/users?format=csv', '/users/2', '/users/999', '/users/2/profile', '/users/2/export', '/rooms', '/games', '/games?format=csv', '/games/cleanup',
            '/async', '/ratings', '/ratings?metric=wins', '/ratings?format=csv', '/ratings/suspicious', '/daily', '/daily?date=2026-01-01', '/daily?date=x',
            '/daily/archive', '/dictionary/word?w=alma', '/dictionary/word?w=', '/dictionary/word?w=falim', '/dictionary/word?w=kg',
            '/dictionary/rejected', '/dictionary/rejected?q=gyűlölet', '/dictionary/rejected?format=csv', '/dictionary/rejected/download', '/dictionary/rejected/download?diff=1',
            '/dictionary/overrides', '/dictionary/additions', '/dictionary/reviewers', '/dictionary/review-summary', '/dictionary/threshold',
            '/reports', '/reports/1', '/moderation/chat', '/moderation/chat?source=log', '/moderation/words', '/moderation/names',
            '/announcements', '/maintenance', '/email/preview?group=recent', '/email/preview?group=all', '/email/preview?group=zzz', '/settings',
            '/stats?metric=registrations', '/stats?metric=active&range=7', '/stats?metric=retention', '/stats?metric=games', '/stats?metric=bots',
            '/stats?metric=words', '/stats?metric=challenges', '/stats?metric=practice', '/stats?metric=review', '/stats?metric=heatmap',
            '/stats?metric=zzz', '/stats?metric=games&format=csv', '/security/logins', '/security/logins?format=csv', '/security/rate-limits', '/security/ip-bans',
            '/security/codes', '/security/sessions', '/system', '/system/logs', '/system/logs?level=ERROR', '/system/logs?level=ZZZ', '/system/cleanup', '/system/mail',
            '/system/update', '/audit', '/audit?limit=2&offset=1', '/audit?action=user', '/audit?format=csv', '/audit?format=zzz']
    for p in GETS:
        A('GET ' + p, 'GET', p)
    # --- írások (sudo nélkül) ---
    A('ban nosudo', 'POST', '/users/2/ban', {'until': '1d', 'reason': 'teszt ok'})
    A('reset nosudo', 'POST', '/users/2/reset-password', {'reason': 'teszt ok'})
    A('email patch nosudo', 'PATCH', '/users/2', {'email': 'uj2@example.com', 'reason': 'teszt ok'})
    A('rating nosudo', 'POST', '/users/2/rating', {'rating': 1300, 'reason': 'teszt'})
    A('delete nosudo', 'DELETE', '/users/3', {'confirm_name': 'Jatekos3', 'reason': 'teszt ok'})
    A('settings nosudo', 'PATCH', '/settings', {'changes': {'bots_enabled': False}, 'reason': 'teszt ok'})
    A('sudo wrong', 'POST', '/sudo', {'password': 'rossz'})
    A('sudo empty', 'POST', '/sudo', {})
    A('sudo', 'POST', '/sudo', {'password': 'secret12'})
    A('session sudo', 'GET', '/session')
    # --- felhasználók ---
    A('ban no reason', 'POST', '/users/2/ban', {'until': '1d'})
    A('ban short reason', 'POST', '/users/2/ban', {'until': '1d', 'reason': 'ab'})
    A('ban bad until', 'POST', '/users/2/ban', {'until': 'zzz', 'reason': 'teszt ok'})
    A('ban admin', 'POST', '/users/7/ban', {'until': '1d', 'reason': 'teszt ok'})
    A('ban missing', 'POST', '/users/999/ban', {'until': '1d', 'reason': 'teszt ok'})
    A('ban', 'POST', '/users/2/ban', {'until': '1d', 'reason': 'teszt ok'})
    A('ban again', 'POST', '/users/2/ban', {'until': '7d', 'reason': 'teszt ok'})
    rn.call('banned me', 'GET', '/api/auth/me', who='u2')
    rn.call('banned login', 'POST', '/api/auth/login', who='u2b', json_body={'email': 'u2@example.com', 'password': 'secret12'})
    A('detail banned', 'GET', '/users/2')
    A('unban', 'POST', '/users/2/unban', {'reason': 'teszt vége'})
    A('unban again', 'POST', '/users/2/unban', {'reason': 'teszt vége'})
    A('mute', 'POST', '/users/3/mute', {'until': '1h', 'reason': 'teszt ok'})
    A('mute bad', 'POST', '/users/3/mute', {'until': 'x', 'reason': 'teszt ok'})
    A('unmute', 'POST', '/users/3/unmute', {'reason': 'teszt ok'})
    A('rating low', 'POST', '/users/3/rating', {'rating': 5, 'reason': 'teszt ok'})
    A('rating', 'POST', '/users/3/rating', {'rating': 1337, 'reason': 'teszt ok'})
    A('note', 'POST', '/users/3/notes', {'note': 'jegyzet'})
    A('note empty', 'POST', '/users/3/notes', {'note': '  '})
    A('note delete', 'DELETE', '/users/3/notes/1')
    A('note delete 404', 'DELETE', '/users/3/notes/99')
    A('badge grant', 'POST', '/users/3/badges', {'badge': 'first_game', 'grant': True, 'reason': 'teszt'})
    A('badge bad', 'POST', '/users/3/badges', {'badge': 'zzz', 'grant': True, 'reason': 'teszt'})
    A('badge revoke', 'POST', '/users/3/badges', {'badge': 'first_game', 'grant': False, 'reason': 'teszt'})
    A('rename', 'PATCH', '/users/3', {'display_name': 'Harmadik', 'reason': 'teszt ok'})
    A('rename bad', 'PATCH', '/users/3', {'display_name': '<b>', 'reason': 'teszt ok'})
    A('rename dup', 'PATCH', '/users/3', {'display_name': 'Jatekos1', 'reason': 'teszt ok'})
    A('rename empty body', 'PATCH', '/users/3', {})
    A('email change', 'PATCH', '/users/3', {'email': 'uj3@example.com', 'reason': 'teszt ok'})
    A('email change bad', 'PATCH', '/users/3', {'email': 'nemcim', 'reason': 'teszt ok'})
    A('email change dup', 'PATCH', '/users/3', {'email': 'u1@example.com', 'reason': 'teszt ok'})
    A('recompute', 'POST', '/users/3/recompute-stats', {'reason': 'teszt ok'})
    A('reviews block', 'POST', '/users/3/reviews/block', {'blocked': True, 'reason': 'teszt ok'})
    A('reviews revert', 'POST', '/users/3/reviews/revert', {'reason': 'teszt ok'})
    A('push test', 'POST', '/users/3/push-test')
    A('reset password', 'POST', '/users/3/reset-password', {'reason': 'teszt ok'})
    A('logout-all', 'POST', '/users/4/logout-all', {'reason': 'teszt ok'})
    A('delete wrong name', 'DELETE', '/users/5', {'confirm_name': 'Rossz', 'reason': 'teszt ok'})
    A('delete anonymize', 'DELETE', '/users/5', {'confirm_name': 'Jatekos5', 'reason': 'teszt ok'})
    A('detail deleted', 'GET', '/users/5')
    A('users list after', 'GET', '/users')
    A('export', 'GET', '/users/3/export')
    A('sudo end', 'DELETE', '/sudo')
    print('1. fázis kész', flush=True)

def scenario2(rn):
    def A(label, method, path, body=None, who='admin'):
        return rn.call(label, method, '/api/admin' + path, who=who, json_body=body, admin=True)
    rn.call('login admin', 'POST', '/api/auth/login', who='admin', json_body={'email': 'admin@example.com', 'password': 'secret12'})
    A('sudo', 'POST', '/sudo', {'password': 'secret12'})
    # beállítások, közlemények, karbantartás
    A('settings bad key', 'PATCH', '/settings', {'changes': {'zzz': 1}, 'reason': 'teszt ok'})
    A('settings empty', 'PATCH', '/settings', {'changes': {}, 'reason': 'teszt ok'})
    A('settings no reason', 'PATCH', '/settings', {'changes': {'bots_enabled': False}})
    A('settings range', 'PATCH', '/settings', {'changes': {'max_bots': 99}, 'reason': 'teszt ok'})
    A('settings type', 'PATCH', '/settings', {'changes': {'max_bots': 'x'}, 'reason': 'teszt ok'})
    A('settings ok', 'PATCH', '/settings', {'changes': {'bots_enabled': False, 'max_spectators': 5}, 'reason': 'teszt ok'})
    A('settings get', 'GET', '/settings')
    A('settings reset', 'PATCH', '/settings', {'changes': {'bots_enabled': None, 'max_spectators': None}, 'reason': 'teszt ok'})
    A('settings limits', 'PATCH', '/settings', {'changes': {'rate_limits_http': {'login': [20, 300]}}, 'reason': 'teszt ok'})
    A('settings limits bad', 'PATCH', '/settings', {'changes': {'rate_limits_http': {'zzz': [1, 1]}}, 'reason': 'teszt ok'})
    A('settings limits reset', 'PATCH', '/settings', {'changes': {'rate_limits_http': None}, 'reason': 'teszt ok'})
    A('ann create', 'POST', '/announcements', {'kind': 'info', 'text_hu': 'Szia', 'text_en': 'Hi', 'audience': 'all'})
    A('ann create bad', 'POST', '/announcements', {'kind': 'zzz', 'text_hu': 'Szia'})
    A('ann create empty', 'POST', '/announcements', {'kind': 'info'})
    A('ann create ends', 'POST', '/announcements', {'kind': 'warning', 'text_hu': 'Hamarosan', 'audience': 'registered', 'ends_at': '2099-01-01 00:00:00'})
    A('ann list', 'GET', '/announcements')
    rn.call('public ann', 'GET', '/api/announcements'); rn.call('public ann u1', 'GET', '/api/announcements', who='u1')
    A('ann patch', 'PATCH', '/announcements/1', {'text_hu': 'Módosított'})
    A('ann patch 404', 'PATCH', '/announcements/99', {'text_hu': 'x'})
    A('ann revoke', 'DELETE', '/announcements/2')
    A('maint on', 'POST', '/maintenance', {'enabled': True, 'message_hu': 'Karbantartás', 'message_en': 'Maint', 'reason': 'teszt ok'})
    rn.call('public maint', 'GET', '/api/announcements')
    A('maint get', 'GET', '/maintenance')
    A('maint off', 'POST', '/maintenance', {'enabled': False, 'reason': 'teszt ok'})
    A('maint bad', 'POST', '/maintenance', {'enabled': 'x', 'reason': 'teszt ok'})
    # push / email
    A('push preview', 'POST', '/push/preview', {'target': 'all', 'title': 'T', 'body': 'B'})
    A('push preview bad', 'POST', '/push/preview', {'target': 'zzz', 'title': 'T', 'body': 'B'})
    A('push send', 'POST', '/push', {'target': 'all', 'title': 'T', 'body': 'B'})
    A('email user', 'POST', '/email', {'user_id': 2, 'subject': 'Teszt', 'body': 'Szia'})
    A('email user bad', 'POST', '/email', {'user_id': 'x', 'subject': 'Teszt', 'body': 'Szia'})
    A('email bulk', 'POST', '/email/bulk', {'group': 'recent', 'subject': 'Teszt', 'body': 'Szia', 'reason': 'teszt ok'})
    # szótár
    A('rejected preview', 'POST', '/dictionary/rejected/preview', {'words': 'almafa\nkörte\nzzzz\nalma'})
    A('rejected add none', 'POST', '/dictionary/rejected', {'words': 'zzzz', 'reason': 'teszt ok'})
    A('rejected add', 'POST', '/dictionary/rejected', {'words': 'almafa', 'reason': 'teszt ok'})
    A('rejected list', 'GET', '/dictionary/rejected?q=almafa')
    A('check rejected', 'GET', '/dictionary/word?w=almafa')
    rn.call('public check rejected', 'GET', '/api/dictionary/check?q=almafa')
    A('rejected diff', 'GET', '/dictionary/rejected/download?diff=1')
    A('rejected remove', 'DELETE', '/dictionary/rejected', {'words': 'almafa', 'reason': 'teszt ok'})
    A('override allow', 'POST', '/dictionary/overrides', {'word': 'bleh', 'verdict': 'allow', 'reason': 'teszt ok'})
    A('override bad', 'POST', '/dictionary/overrides', {'word': 'bleh', 'verdict': 'x', 'reason': 'teszt ok'})
    rn.call('public check override', 'GET', '/api/dictionary/check?q=bleh')
    A('override reject', 'POST', '/dictionary/overrides', {'word': 'alma', 'verdict': 'reject', 'reason': 'teszt ok'})
    rn.call('public check override2', 'GET', '/api/dictionary/check?q=alma')
    A('override list', 'GET', '/dictionary/overrides')
    A('override remove', 'DELETE', '/dictionary/overrides', {'word': 'alma', 'reason': 'teszt ok'})
    A('override remove2', 'DELETE', '/dictionary/overrides', {'word': 'bleh', 'reason': 'teszt ok'})
    A('addition add', 'POST', '/dictionary/additions', {'word': 'kakukk', 'reason': 'teszt ok'})
    A('addition list', 'GET', '/dictionary/additions')
    A('addition remove', 'DELETE', '/dictionary/additions', {'word': 'kakukk', 'reason': 'teszt ok'})
    A('votes delete', 'DELETE', '/dictionary/votes', {'word': 'alma', 'reason': 'teszt ok'})
    A('second opinion', 'GET', '/dictionary/second-opinion?n=3')
    A('caches', 'POST', '/dictionary/caches/clear', {'which': 'valid', 'reason': 'teszt ok'})
    A('caches bad', 'POST', '/dictionary/caches/clear', {'which': 'zzz', 'reason': 'teszt ok'})
    # moderáció
    A('mod word add', 'POST', '/moderation/words', {'word': 'csunya', 'reason': 'teszt ok'})
    A('mod word add short', 'POST', '/moderation/words', {'word': 'a', 'reason': 'teszt ok'})
    A('mod words', 'GET', '/moderation/words')
    A('mod word del', 'DELETE', '/moderation/words', {'word': 'csunya', 'reason': 'teszt ok'})
    A('report 404', 'GET', '/reports/99'); A('report patch 404', 'PATCH', '/reports/99', {'status': 'handled', 'reason': 'teszt ok'})
    # biztonság
    A('ip ban', 'POST', '/security/ip-bans', {'ip': '203.0.113.7', 'reason': 'teszt ok'})
    A('ip ban cidr', 'POST', '/security/ip-bans', {'ip': '198.51.100.0/24', 'until': '1d', 'reason': 'teszt ok'})
    A('ip ban bad', 'POST', '/security/ip-bans', {'ip': 'nem-ip', 'reason': 'teszt ok'})
    A('ip ban own', 'POST', '/security/ip-bans', {'ip': '127.0.0.1', 'reason': 'teszt ok'})
    A('ip ban list', 'GET', '/security/ip-bans')
    A('ip unban', 'DELETE', '/security/ip-bans/1', {'reason': 'teszt ok'})
    A('ip unban 404', 'DELETE', '/security/ip-bans/99', {'reason': 'teszt ok'})
    A('unblock', 'POST', '/security/rate-limits/unblock', {'ip': '203.0.113.7', 'reason': 'teszt ok'})
    A('codes', 'GET', '/security/codes'); A('code inv 404', 'DELETE', '/security/codes/99', {'reason': 'teszt ok'})
    A('sessions', 'GET', '/security/sessions'); A('close admins', 'POST', '/security/sessions/close-admins', {'reason': 'teszt ok'})
    print('2. fázis kész', flush=True)

def scenario3(rn):
    def A(label, method, path, body=None, who='admin'):
        return rn.call(label, method, '/api/admin' + path, who=who, json_body=body, admin=True)
    rn.call('login admin', 'POST', '/api/auth/login', who='admin', json_body={'email': 'admin@example.com', 'password': 'secret12'})
    A('sudo', 'POST', '/sudo', {'password': 'secret12'})
    A('backup', 'POST', '/system/backup', {})
    A('backup list', 'GET', '/system')
    A('vacuum', 'POST', '/system/vacuum', {'reason': 'teszt ok'})
    A('cleanup preview', 'GET', '/system/cleanup?days=1')
    A('cleanup', 'POST', '/system/cleanup', {'items': ['sessions', 'codes'], 'days': 1, 'reason': 'teszt ok'})
    A('cleanup bad', 'POST', '/system/cleanup', {'items': ['zzz'], 'reason': 'teszt ok'})
    A('smtp test', 'POST', '/system/smtp-test', {})
    A('mail get', 'GET', '/system/mail')
    A('mail bad', 'PATCH', '/system/mail', {'host': '', 'reason': 'teszt ok'})
    A('mail save', 'PATCH', '/system/mail', {'host': 'localhost', 'port': 2525, 'security': 'none', 'username': '', 'password': '', 'from_address': 'a@b.hu', 'from_name': 'Teszt', 'verify_tls': True, 'reason': 'teszt ok'})
    A('mail get2', 'GET', '/system/mail')
    A('mail reset', 'DELETE', '/system/mail', {'reason': 'teszt ok'})
    A('mail reset again', 'DELETE', '/system/mail', {'reason': 'teszt ok'})
    A('mail check', 'POST', '/system/mail/check', {'host': 'localhost', 'port': 1, 'security': 'none', 'username': '', 'password': '', 'from_address': 'a@b.hu', 'verify_tls': True})
    A('push test self', 'POST', '/system/push-test', {})
    A('update check', 'POST', '/system/update/check', {'fetch': False})
    A('tunnel restart', 'POST', '/system/tunnel/restart', {'reason': 'teszt ok'})
    A('games list', 'GET', '/games'); A('games cleanup', 'POST', '/games/cleanup', {'days': 1, 'reason': 'teszt ok'})
    A('ratings dry', 'POST', '/ratings/recompute', {}); A('ratings apply', 'POST', '/ratings/recompute', {'dry_run': False, 'reason': 'teszt ok'})
    A('async sweep', 'POST', '/async/sweep', {}); A('async 404', 'POST', '/async/99/extend', {'hours': 24, 'reason': 'teszt ok'})
    A('game 404', 'GET', '/games/99'); A('game void 404', 'POST', '/games/99/void', {'reason': 'teszt ok'}); A('game moves 404', 'GET', '/games/99/moves')
    A('daily regen', 'POST', '/daily/2026-10-05/regenerate', {'reason': 'teszt ok'})
    A('daily regen bad', 'POST', '/daily/zzz/regenerate', {'reason': 'teszt ok'})
    A('daily score del', 'DELETE', '/daily/2026-10-05/scores/2', {'reason': 'teszt ok'})
    A('daily reset', 'POST', '/daily/2026-10-05/scores/2/reset-revealed', {'reason': 'teszt ok'})
    A('rooms action 404', 'POST', '/rooms/zzzzzz/action', {'action': 'message', 'message': 'x'})
    A('rooms detail 404', 'GET', '/rooms/zzzzzz')
    A('sessions revoke 404', 'DELETE', '/security/sessions/9999', {'reason': 'teszt ok'})
    A('audit final', 'GET', '/audit?limit=200')
    A('audit actions', 'GET', '/audit?action=settings')
    A('audit csv', 'GET', '/audit?format=csv')

if __name__ == '__main__':
    which = sys.argv[1]
    run_all({'1': scenario, '2': scenario2, '3': scenario3}[which], 'h2_admin' + which, 160)
